##################### Training Control #####################
deterministic: False
use_compile: True
inference_mode: False # If this one is True, use inference
seed: 1234
max_epochs: 40

##################### Distributed Training Control #####################
devices: 1
num_nodes: 1
strategy: auto

##################### Dataset Setting #####################
dataset_class_name: fourier_vec
dataset_dir: '/fs/nexus-scratch/haowenyu/SportsActionUnderstanding/ActionData'
split_ratios: [0.8, 0.1, 0.1]
batch_size: 4
test_batch_size: 2
num_workers: 4
persistent_workers: True
accumulation_interval_ms: 150
use_cache: True
cache_root: '/fs/nexus-scratch/haowenyu/ActionDataCache'
pt_dim: 3 
enc_dim: 128
radius: 1.0
max_events: 100000
downsample_rate: 0.1
purpose: 'train'
mode: 'fast'

##################### Model Architecture #####################
model_class_name: vec_ssm
num_classes: 16
input_dim: 256
ssm_dim: 256
state_dim: 256

##################### Optimizers and Loss Functions #####################
weight_decay: 1e-6
lr: 1e-3
lr_scheduler: step
lr_decay_epochs: 5
lr_decay_rate: 0.5
lr_decay_min_lr: 1e-5

###################### Tensorboard Logger Setting #####################
log_dir: 'lightning_logs'
experiment_name: 'ssm_fourier_vec'

##################### Checkpoint & Restart Control #####################
enable_checkpointing: True